spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    ##### MS 내부 개발 서버(테스트)
    url: jdbc:log4jdbc:mysql://localhost:3306/spring_security?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    sql-script-encoding: UTF-8
    
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    web: info
    root: info
    com.example.demo: info
