apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-visualizer-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-visualizer-auth
  template:
    metadata:
      labels:
        app: batch-visualizer-auth
    spec:
      containers:
        - name: batch-visualizer-auth
          image: sktellecom/kube-repo:batch-visualizer-auth
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate